# Generated by Django 4.2.1 on 2023-10-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_basemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='cashback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='cashback',
            field=models.FloatField(default=0.0),
        ),
    ]
